### PR TITLE
Bug Fix:  OpenCl memory leak

### PR DESCRIPTION
**Pull request by JungleCatSW**
This fixes an open cl memory leak.

To do this it needs somewhere to keep a **cl_context**, it seemed like workers.h was an easy place to put it, I'm not sure if there is a better place to put it...

### CODE REVIEW

**Comment by xmrig** [comment]
`cl_context` declared as `typedef struct _cl_context * cl_context;` so it already a pointer to a struct, don't change it to pointer to a pointer.
Thank you.

**Comment by JungleCatSW** [comment]
Hi I have removed the double pointers! Thanks for feedback.

**Comment by xmrig** [comment]
I saw, thank you, right now too busy to merge it.

**Comment by xmrig** [comment]
Merged. Thank you.

**Pull request merged**
